(function(){
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  let sim=new MorphCore.MorphSimulation({seed:$("#seedInput").value}),renderer=new MorphUI.MorphRenderer($("#labCanvas"));
  let running=false,view="observatory",last=0,acc=0,brush=false;
  const titles={observatory:["LIVE BODY STATE","Observatory","Click a cell to inspect its local state."],signals:["POSITIONAL INPUTS","Signal field","Engineered A/B gradients and center signal."],atlas:["LOCAL CONNECTIVITY","Cell atlas","Near-neighbour links are recalculated from geometry."],interventions:["PERTURBATION TOOLS","Intervention lab","Drag across the body to ablate cells."],experiments:["MATCHED PROTOCOLS","Experiments","Run fixed interventions from a deterministic seed."],archive:["REPRODUCIBLE RUNS","Run archive","Save the current seed, cycle and intervention record."]};
  function metrics(){const m=MorphCore.computeMetrics(sim);$("#metricCells").textContent=m.cells;$("#metricRecovery").textContent=(m.recovery*100).toFixed(1)+"%";$("#metricCoverage").textContent=(m.coverage*100).toFixed(1)+"%";$("#metricEnergy").textContent=m.energy.toFixed(2);$("#metricStress").textContent=m.stress.toFixed(2);$("#metricInterventions").textContent=sim.events.filter(e=>e.type!=="division").length;$("#miniMetrics").textContent=`CYCLE ${String(sim.cycle).padStart(5,"0")} · ${m.cells} CELLS · REC ${(m.recovery*100).toFixed(1)}%`;return m;}
  function setRunning(v){running=v;$("#runBtn").textContent=v?"Pause":"Run";$("#runState").classList.toggle("running",v);$("#runState span:last-child").textContent=v?"RUNNING":"PAUSED";}
  function reset(){setRunning(false);sim=new MorphCore.MorphSimulation({seed:$("#seedInput").value});render();inspector();}
  function render(){renderer.render(sim,view==="interventions"?"observatory":view);metrics();}
  function kv(k,v){return `<span>${k}</span><span>${v}</span>`}
  function bar(n,v){return `<div class="signal-row"><span>${n}</span><span class="bar"><i style="width:${Math.max(0,Math.min(100,v*100))}%"></i></span><b>${v.toFixed(2)}</b></div>`}
  function inspector(){const box=$("#inspectorContent");if(view==="experiments"){box.innerHTML=`<div class="panel-kicker">FIXED PROTOCOL SET</div><div class="intro-card"><p>Each protocol resets the same seed, runs a 250-cycle warm-up, applies one intervention, then advances to cycle 900.</p></div><div class="stack">${MorphExperiments.protocols.map((p,i)=>`<div class="protocol"><div class="protocol-head"><strong>${p.name}</strong><code>${p.id}</code></div><p>${p.question}</p><button class="small-btn" data-protocol="${i}">RUN MATCHED TRIAL</button></div>`).join("")}</div>`;$$('[data-protocol]').forEach(b=>b.onclick=()=>runProtocol(+b.dataset.protocol));return}
    if(view==="archive"){const entries=JSON.parse(localStorage.getItem("morph-runs")||"[]");box.innerHTML=`<div class="panel-kicker">RUN ARCHIVE</div><div class="intro-card"><p>Runs preserve the seed, cycle and intervention schedule. They can be exported as JSON.</p><button class="small-btn" id="saveRun">SAVE CURRENT RUN</button> <button class="small-btn" id="exportRun">EXPORT JSON</button></div>${entries.length?entries.map((e,i)=>`<div class="archive-entry"><b>${e.seed} · cycle ${e.cycle}</b><span>${e.events.length} recorded intervention(s)</span><br><button class="small-btn" data-load="${i}">LOAD</button></div>`).join(""):"<p class='mono' style='color:#777;font-size:11px'>No saved runs yet.</p>"}`;$("#saveRun").onclick=saveRun;$("#exportRun").onclick=exportRun;$$('[data-load]').forEach(b=>b.onclick=()=>loadRun(+b.dataset.load));return}
    if(view==="interventions"){box.innerHTML=`<div class="panel-kicker">MANUAL ABLATION</div><div class="brush-help">Hold the pointer and drag across the organism. Cells within the ablation brush are removed from the simulation. Repair begins immediately.</div><div class="panel-rule"></div><div class="panel-kicker">FIXED PERTURBATIONS</div><div class="stack" style="margin-top:10px"><button class="control danger" data-int="incision">Incision</button><button class="control" data-int="signalLoss">Signal A off</button><button class="control" data-int="starvation">Starvation</button><button class="control" data-int="polarityFlip">Polarity flip</button><button class="control" data-int="randomPolicy">Random policy</button><button class="control" data-int="signalNoise">Signal noise</button><button class="control danger" data-int="split">Split body</button></div>`;$$('[data-int]').forEach(b=>b.onclick=()=>{MorphCore.interventions[b.dataset.int](sim);render();});return}
    if(view==="signals"){box.innerHTML=`<div class="panel-kicker">FIELD LEGEND</div><div class="legend" style="margin-top:12px"><div class="legend-row"><i class="legend-dot" style="background:#95c6dc"></i> Morphogen A · left high</div><div class="legend-row"><i class="legend-dot" style="background:#e2a1b0"></i> Morphogen B · right high</div><div class="legend-row"><i class="legend-dot" style="background:#a7c99e"></i> Center signal · radial</div></div><div class="panel-rule"></div><div class="intro-card"><p>These are engineered scalar fields used as local positional inputs. They are not measurements from biological tissue.</p></div>`;return}
    if(view==="atlas"){box.innerHTML=`<div class="panel-kicker">CELL ATLAS</div><div class="intro-card"><p>Lines connect cells closer than the local interaction radius. Select a node to inspect its energy, stress, local signals and neighbour count.</p></div>`}
    const c=sim.living().find(c=>c.id===sim.selected);if(c){box.innerHTML+=`<div class="panel-kicker">SELECTED CELL</div><div class="cell-title-row"><h3>CELL ${String(c.id).padStart(3,"0")}</h3><span class="status-chip">ALIVE</span></div><div class="kv-grid">${kv("parent",c.parent??"founder")}${kv("age",c.age)}${kv("energy",c.energy.toFixed(3))}${kv("stress",c.stress.toFixed(3))}${kv("neighbors",c.neighbors)}${kv("target Δ",Math.hypot(c.x-c.targetX,c.y-c.targetY).toFixed(1))}</div><div class="panel-rule"></div><div class="panel-kicker">LOCAL INPUTS</div><div class="signal-bars">${bar("morphogen A",c.signalA)}${bar("morphogen B",c.signalB)}${bar("center",c.centerSignal)}${bar("nutrient",c.nutrient)}</div>`}else if(view==="observatory"||view==="atlas")box.innerHTML+=`<div class="panel-kicker">NO CELL SELECTED</div><div class="intro-card"><p>Click a visible cell to inspect the local state driving its next update.</p></div>`;
  }
  function setView(v){view=v;$$('.tab').forEach(b=>b.classList.toggle('is-active',b.dataset.view===v));const t=titles[v];$("#viewEyebrow").textContent=t[0];$("#viewTitle").textContent=t[1];$("#stageNote").textContent=t[2];$("#canvasBadge").textContent=v==="signals"?"ENGINEERED SIGNAL FIELD · MODEL VIEW":"MODEL VIEW · NOT BIOLOGICAL IMAGING";inspector();render();}
  function runProtocol(i){setRunning(false);const p=MorphExperiments.protocols[i];sim=new MorphCore.MorphSimulation({seed:$("#seedInput").value});sim.run(250);p.apply(sim);sim.run(650);const m=MorphCore.computeMetrics(sim);view="observatory";$$('.tab').forEach(b=>b.classList.toggle('is-active',b.dataset.view===view));const t=titles[view];$("#viewEyebrow").textContent=`RESULT · ${p.id}`;$("#viewTitle").textContent=p.name;$("#stageNote").textContent=`Recovery ${(m.recovery*100).toFixed(1)}% · coverage ${(m.coverage*100).toFixed(1)}%`;inspector();render();}
  function saveRun(){const arr=JSON.parse(localStorage.getItem("morph-runs")||"[]"),record=JSON.parse(sim.exportRun());arr.unshift(record);localStorage.setItem("morph-runs",JSON.stringify(arr.slice(0,12)));inspector();}
  function exportRun(){const blob=new Blob([sim.exportRun()],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`morph-run-${sim.seed}-${sim.cycle}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
  function loadRun(i){const arr=JSON.parse(localStorage.getItem("morph-runs")||"[]");if(!arr[i])return;sim=MorphCore.MorphSimulation.replay(arr[i]);$("#seedInput").value=sim.seed;setView("observatory");}
  $("#runBtn").onclick=()=>setRunning(!running);$("#stepBtn").onclick=()=>{sim.step();render();};$("#resetBtn").onclick=reset;$$('.tab').forEach(b=>b.onclick=()=>setView(b.dataset.view));$("#seedInput").addEventListener('change',reset);window.addEventListener('resize',()=>{renderer.resize();render()});
  const canvas=$("#labCanvas");canvas.addEventListener('pointerdown',e=>{if(view==="interventions"){brush=true;const p=renderer.simPoint(sim,e.clientX,e.clientY);sim.ablateCircle(p.x,p.y,33);render()}else{const c=renderer.nearest(sim,e.clientX,e.clientY);sim.selected=c?c.id:null;inspector();render()}});canvas.addEventListener('pointermove',e=>{if(brush&&view==="interventions"){const p=renderer.simPoint(sim,e.clientX,e.clientY);sim.ablateCircle(p.x,p.y,25);render()}});window.addEventListener('pointerup',()=>brush=false);
  function frame(ts){const dt=Math.min(40,ts-last||16);last=ts;if(running){acc+=dt;const speed=+$("#speedSelect").value;const every=34/Math.max(1,speed);while(acc>every){sim.step();acc-=every}render()}requestAnimationFrame(frame)}
  renderer.resize();inspector();render();requestAnimationFrame(frame);
})();
